### ISSUE TITLE
Change documentation to markdown

### ISSUE THREAD

**Issue by ElectricCoffee** [ludat/hado-rs#1]
I can see you're using orgmode, and that's totally awesome!

However, it appears that crates.io doesn't support orgmode syntax in its documentation; so it looks like an absolute mess.

I would advise you to convert it to markdown just for the sake of those unfamiliar with orgmode notation

**Comment by ludat** [comment]
Done :smiley: 

How did you find this repo?

**Comment by ElectricCoffee** [comment]
I tried to look for IO monad implementations on the site; ended up finding this insead
